// UI integration contract test. Responses are deliberately mocked; not a live Supabase test.
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'msedge'});
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const user={id:'00000000-0000-0000-0000-000000000010',email:'admin@example.test',aud:'authenticated',role:'authenticated',created_at:new Date().toISOString(),app_metadata:{},user_metadata:{}};
const token=`${Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url')}.${Buffer.from(JSON.stringify({sub:user.id,exp:Math.floor(Date.now()/1000)+3600,role:'authenticated'})).toString('base64url')}.fixture`;
const tables={products:[],portfolio_items:[],blog_posts:[],looks:[],look_products:[],creator_settings:[],smart_links:[],testimonials:[],brand_collaborations:[],collaboration_inquiries:[],contact_messages:[],analytics_events:[],affiliate_clicks:[]};
await page.route('https://fixture.supabase.co/**',async route=>{const req=route.request();const u=new URL(req.url());const respond=(body,status=200,extra={})=>route.fulfill({status,contentType:'application/json',headers:{'access-control-allow-origin':'*',...extra},body:JSON.stringify(body)});if(req.method()==='OPTIONS')return respond({});if(u.pathname.includes('/auth/v1/token'))return respond({access_token:token,refresh_token:'fixture-refresh-token',expires_in:3600,token_type:'bearer',user});if(u.pathname.includes('/auth/v1/user'))return respond(user);if(u.pathname.endsWith('/rpc/is_admin'))return respond(true);if(u.pathname.endsWith('/rpc/admin_analytics'))return respond({product_clicks:[],campaign_clicks:[],source_clicks:[],product_views:[],brand_enquiries:[]});if(u.pathname.includes('/functions/v1/'))return respond({ok:true});if(u.pathname.includes('/storage/v1/object/'))return respond({Key:'fixture.webp'});const table=u.pathname.split('/').at(-1);if(!(table in tables))return respond({});if(req.method()==='HEAD')return route.fulfill({status:200,headers:{'content-range':`0-0/${tables[table].length}`}});if(req.method()==='GET')return respond(tables[table]);if(req.method()==='POST'){const row=req.postDataJSON();const id=row.id||crypto.randomUUID();const existing=tables[table].findIndex(x=>x.id===id);const value={...row,id,created_at:new Date().toISOString()};if(existing>=0)tables[table][existing]={...tables[table][existing],...value};else tables[table].push(value);return respond(null,201);}if(req.method()==='DELETE'){tables[table]=tables[table].filter(x=>`eq.${x.id}`!==u.searchParams.get('id'));return respond(null);}return respond({});});
await page.goto('http://127.0.0.1:5174/admin/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.test');await page.getByLabel('Password').fill('fixture-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/admin');
await page.getByRole('link',{name:'Products',exact:true}).click();await page.getByRole('button',{name:'Add new'}).click();await page.getByLabel('Product name',{exact:true}).fill('Fixture lipstick');await page.getByLabel('Product category').selectOption('Makeup');await page.getByLabel('Affiliate link', {exact:true}).fill('https://retailer.example/lipstick');await page.getByLabel('Demo product',{exact:true}).uncheck();await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('cell',{name:'Fixture lipstick',exact:true}).waitFor();assert.equal(tables.products[0].price,null);assert.equal(tables.products[0].active,true);
await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Price (optional)').fill('499');await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('cell',{name:'Fixture lipstick',exact:true}).waitFor();assert.equal(tables.products[0].price,499);
await page.getByRole('link',{name:'Portfolio',exact:true}).click();await page.getByRole('button',{name:'Add new'}).click();await page.getByLabel('Title',{exact:true}).fill('Fixture Reel');await page.getByLabel('URL slug').fill('fixture-reel');await page.getByLabel('Content URL').fill('https://www.instagram.com/reel/fixture/');await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('cell',{name:'Fixture Reel',exact:true}).waitFor();assert.equal(tables.portfolio_items[0].published_date,null);assert.equal(tables.portfolio_items[0].views,null);
await page.getByRole('link',{name:'Blog',exact:true}).click();await page.getByRole('button',{name:'Add new'}).click();await page.getByLabel('Title',{exact:true}).fill('Fixture article');await page.getByLabel('URL slug').fill('fixture-article');await page.getByLabel('Article (Markdown)').fill('## A real heading\nThis is a test fixture.');await page.getByLabel('Status',{exact:true}).selectOption('published');await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('cell',{name:'Fixture article',exact:true}).waitFor();assert.ok(tables.blog_posts[0].published_at);
await page.getByRole('link',{name:'Shop the Look',exact:true}).click();await page.getByRole('button',{name:'Add new'}).click();await page.getByLabel('Title',{exact:true}).fill('Fixture look');await page.getByLabel('Product category').selectOption('Makeup');await page.getByLabel('Affiliate link', {exact:true}).fill('https://retailer.example/look?tag=creator');await page.getByLabel('Reel URL').fill('https://www.instagram.com/reel/fixture/');await page.getByLabel('Published',{exact:true}).check();await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('cell',{name:'Fixture look',exact:true}).waitFor();await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Product to add to look').selectOption(tables.products[0].id);await page.getByRole('button',{name:'Add product',exact:true}).click();await page.getByRole('button',{name:'Remove from look'}).waitFor();assert.equal(tables.look_products.length,1);
const lookPage = await browser.newPage();await lookPage.route('https://fixture.supabase.co/**', async route => { const table = new URL(route.request().url()).pathname.split('/').at(-1);await route.fulfill({contentType:'application/json', body:JSON.stringify(tables[table] || [])}); });tables.looks[0].title = 'Professional Makeup Brushes - Travel Set for Foundation, Powder, Concealer, Eyeshadow, Blush and Highlighter';await lookPage.setViewportSize({width:1440,height:1000});await lookPage.goto(`http://127.0.0.1:5174/looks/${tables.looks[0].slug}`);await lookPage.getByRole('link',{name:'Watch Reel',exact:true}).waitFor();assert.equal(await lookPage.getByRole('link',{name:'Buy now'}).getAttribute('href'),'https://retailer.example/look?tag=creator');await lookPage.screenshot({path:'outputs/affiliate-look-desktop.png',fullPage:true});await lookPage.setViewportSize({width:390,height:844});await lookPage.screenshot({path:'outputs/affiliate-look-mobile.png',fullPage:true});assert.equal(await lookPage.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true);await lookPage.close();tables.looks[0].title='Fixture look';await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Keep it'}).click();assert.equal(tables.looks.length,1);await page.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete record',exact:true}).click();await page.getByText('No shop the look yet.').waitFor();assert.equal(tables.looks.length,0);
await page.goto(`http://127.0.0.1:5174/shop/${tables.products[0].slug}`);await page.getByRole('heading',{name:'Fixture lipstick',exact:true}).waitFor();await page.getByRole('link',{name:'Shop now'}).waitFor();
assert.deepEqual(errors,[]);console.log('Mocked admin UI checks passed: sign-in, product create/edit, optional null values, portfolio create, blog publish, look/product assignment, delete confirmation, product detail and affiliate CTA.');await browser.close();
